import Head from 'next/head';
import Feed from '../components/Feed';
import Modal from '../components/Modal';
import Sidebar from '../components/Sidebar';
import Header from '../components/Header';
import Widgets from '../components/Widgets';
import { getSession, useSession } from 'next-auth/react';
import { AnimatePresence } from 'framer-motion';
import { useRouter } from 'next/router';
import { modalState, modalTypeState } from '../atoms/modalAtom';
import { useRecoilState } from 'recoil';
import { connectToDatabase } from '../util/mongodb';

export default function Home({ posts, articles }) {
  const [modalOpen, setModalOpen] = useRecoilState(modalState);
  const [modalType, setModalType] = useRecoilState(modalTypeState);
  const router = useRouter();
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      router.push('/home');
    },
  });

  const { data: session } = useSession();

  return (
    <div className="bg-[#F3F2EF] dark:bg-black dark:text-white h-screen overflow-y-scroll md:space-y-6">
      <Head>
        <title>LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="flex justify-center gap-x-5 px-4 sm:px-12">
        <div className="flex flex-col md:flex-row gap-5">
          <Sidebar session={session} />
          <Feed posts={posts} />
        </div>
        <Widgets articles={articles} />
        <AnimatePresence>
          {modalOpen && (
            <Modal handleClose={() => setModalOpen(false)} type={modalType} />
          )}
        </AnimatePresence>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: { permanent: false },
      destination: '/home',
    };
  }

  //Get posts on SSR

  const { db } = await connectToDatabase();

  const posts = await db
    .collection('posts')
    .find()
    .sort({ timestamp: -1 })
    .toArray();

  // Get Google News API
  const results = await fetch(`
  https://newsapi.org/v2/top-headlines?country=br&apiKey=${process.env.NEWS_API_KEY}
  `).then((response) => response.json());

  return {
    props: {
      session,
      articles: results?.articles,
      posts: posts.map((post) => ({
        _id: post._id.toString(),
        input: post.input,
        photoUrl: post.photoUrl,
        username: post.username,
        email: post.email,
        userImg: post.userImg,
        createdAt: post.createdAt,
      })),
    },
  };
}
